
title: 浮生偶记
subtitle: 听风 | 聆月 | 写代码
timezone: Asia/Shanghai

author: moonlightwatch
email: moonlightwatch@hotmail.com

paginate: 10
paginate_path: "/page:num"

markdown: kramdown
highlighter: rouge


plugins:
  - jekyll-paginate

gitalk:
  clientID: 2584221be2ce79685562
  clientSecrets: 72c84aa79198b292b62ed75b960547fc28439814
  repo: moonlightwatch.github.io
  owner: moonlightwatch
  
