
title: MoonLightWatch's Blog
timezone: Asia/Shanghai

paginate: 10
paginate_path: "/page:num"


plugins:
  - jemoji
  - jekyll-paginate

gitalk:
  clientID: 2065d0dbea93a4ae42c7
  clientSecrets: 72168c8442387993b970dbc40d181f35dad8c680
  repo: moonlightwatch.github.io
  owner: moonlightwatch
  
